"""initial migration

Revision ID: 3292585e814e
Revises: 
Create Date: 2026-03-21 15:56:46.127790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3292585e814e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
