"""add index comercio_id produtos

Revision ID: 8bec6b1f0322
Revises: 3292585e814e
Create Date: 2026-03-22 19:41:58.969049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bec6b1f0322'
down_revision = '3292585e814e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_comercio_id'), ['comercio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_comercio_id'))

    # ### end Alembic commands ###
